### ISSUE TITLE
Add table gcp_billingAccounts

### ISSUE THREAD

**Issue by slagathorr** [turbot/steampipe-plugin-gcp#354] opened 2022-03-30 15:44 UTC
Being able to query billing account information would be helpful.

https://cloud.google.com/billing/docs/reference/rest/v1/billingAccounts
https://cloud.google.com/billing/docs/reference/libraries#client-libraries-install-go
https://cloud.google.com/sdk/gcloud/reference/alpha/billing/accounts

**Comment by bigdatasourav** [comment] 2023-06-12 07:22
@slagathorr First and foremost, I sincerely apologize for the prolonged silence on this issue. We understand the importance of addressing your concerns quickly and apologize for any inconvenience caused by the delay.

After thorough investigation and research, it has been determined that the APIs provided by GCP for cost management, such as the Cloud Billing Budgets and Alerts API, GCP Billing Accounts API, and Cost Estimation API, do not offer actual cost and usage information. These APIs serve specific purposes related to cost management but do not provide real-time or detailed data on actual cost and resource usage.

We are closing this issue for now, considering the available options and information gathered. However, we are still open to any suggestions or feedback you may have regarding cost management in GCP. Your input is valuable to us, and we appreciate your understanding and patience.

Once again, we sincerely apologize for the delay in addressing this matter. If you have any further questions or concerns, please don't hesitate to reach out.

**Comment by cbruno10** [comment] 2023-06-13 13:16
We're resuming work on the billing tables that were already WIP, reopening this issue.

**Closed** 2023-06-15 07:12 UTC
Labels: enhancement, new table
